src/Entity/Prof.php
<?php

namespace App\Entity;

use App\Repository\ProfRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProfRepository::class)
 */
class Prof
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_de_naissance;

    /**
     * @ORM\ManyToOne(targetEntity=Matiere::class, inversedBy="profs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $matiere;

    /**
     * @ORM\OneToMany(targetEntity=Classe::class, mappedBy="prof", orphanRemoval=true)
     */
    private $classes;

    public function __construct()
    {
        $this->classes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(?\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getMatiere(): ?Matiere
    {
        return $this->matiere;
    }

    public function setMatiere(?Matiere $matiere): self
    {
        $this->matiere = $matiere;

        return $this;
    }

    /**
     * @return Collection<int, Classe>
     */
    public function getClasses(): Collection
    {
        return $this->classes;
    }

    public function addClass(Classe $class): self
    {
        if (!$this->classes->contains($class)) {
            $this->classes[] = $class;
            $class->setProf($this);
        }

        return $this;
    }

    public function removeClass(Classe $class): self
    {
        if ($this->classes->removeElement($class)) {
            // set the owning side to null (unless already changed)
            if ($class->getProf() === $this) {
                $class->setProf(null);
            }
        }

        return $this;
    }

    
}

src/Controller/ProfController.php
<?php

namespace App\Controller;

use App\Entity\Prof;
use App\Repository\ProfRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProfController extends AbstractController
{
    /**
     * @Route("/profs", name="app_profs")
     */
    public function liste(ProfRepository $pr): Response
    {
        return $this->render('prof/profs.html.twig', [
            'profs' => $pr->findAll()
        ]);
    }

    /**
     * @Route("/prof/create", name="app_prof_create")
     */
    public function create(ProfRepository $cr, Request $request)
    {
        $prof = new Prof;
        $formulaire = $this
            ->createFormBuilder($prof)
            ->add('nom', TextType::class)
            ->add('prenom', TextType::class)
            ->add('date_de_naissance', DateType::class)
            ->add('matiere', TextType::class)
            ->add(
                'submit',
                SubmitType::class,
                ['label' => 'Envoyer']
            )
            ->getForm();
        $formulaire->handleRequest($request);

        if ($formulaire->isSubmitted() && $formulaire->isValid()) {

            $cr->add($prof);
            return $this->redirectToRoute('app_profs');
        } else return $this->render('prof/create.html.twig', [
            'formView' => $formulaire->createView()
        ]);
    }

    /**
     * @Route("/prof/{id}/delete", name="app_prof_delete")
     */
    public function delete($id, ProfRepository $pr): Response
    {
        $pr->remove($pr->find($id));

        return $this->redirectToRoute('app_profs');
    }
}

templates/prof/create.html.twig
<!doctype html>
<html lang="fr">

<head>
    <title>Formulaire prof</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
    <h1>Formulaire professeur</h1>
    
    <div class="container">
        {{ form(formView) }}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/prof/profs.html.twig
<!doctype html>
<html lang="fr">

<head>
  <title>page 1</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <nav class="nav justify-content-center">
    <a class="nav-link active" href="{{path('accueil')}}">Accueil</a>
    <a class="nav-link active" href="{{path('app_eleves')}}">Les élèves</a>
    <a class="nav-link active" href="{{path('app_classes')}}">Les classes</a>
    <a class="nav-link active" href="{{path('app_matieres')}}">Les matiéres</a>
    <a class="nav-link active" href="{{path('app_prof_create')}}">Creation de professeurs</a>
  </nav>

  <h1>Les professeurs</h1>

  <dl>
    {% for prof in profs %}
    <dt>Nom :</dt>
    <dd>{{ prof.nom }}</dd>

    <dt>Prenom :</dt>
    <dd>{{ prof.prenom }}</dd>

    <dt>Date de naissance :</dt>
    <dd>{{ prof.dateDeNaissance|date('d/m/Y') }}</dd>

    <dt>Matiére :</dt>
    <dd>{{ prof.matiere.nom }}</dd>

    <dd>
      <a href="{{path('app_prof_delete', {id: prof.id})}}" class="btn btn-danger" onclick="return confirm('Etes-vous ok pour supprimer???')">Supprimer</a>
               <i class="fa fa-trash" aria-hidden="true"></i>
    </dd>
    {% endfor %}
  </dl>


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
</body>

</html>